//
// Generated by Microsoft (R) D3DX9 Shader Compiler 9.12.589.0000
//
//   fxc /T ps_1_4 /E main /Fc bump.asm /Fo bump.pso bump.psh
//
//
// Parameters:
//
//   sampler2D BumpMapSampler;
//   sampler2D ColorMapSampler;
//   float4 cAmbient;
//   float4 cSpecular;
//
//
// Registers:
//
//   Name            Reg   Size
//   --------------- ----- ----
//   cAmbient        c0       1
//   cSpecular       c1       1
//   ColorMapSampler s0       1
//   BumpMapSampler  s1       1
//

    ps_1_4
    texcrd r0.xyz, t4
    texld r1, t0
    dp3_sat r0.w, r1_bx2, r0
    mul r0.w, r0.w, r0.w
    mul r0.w, r0.w, r0.w
    mul r0.w, r0.w, r0.w
    mul r2.w, r0.w, r0.w
    mul r2.w, r2.w, r2.w
    mul r0.w, r0.w, r2.w
  + mov r2.xyz, r1
    mov r3.x, r0.w
    phase
    texld r0, t0
    texcrd r1.xyz, t2
    mov r3.w, r3.x
    dp3_sat r1.w, r2_bx2, r1
    mul_sat r2, r3.w, c1
    mul r3, r0, c0
    mad r0, r0, r1.w, r3
    add r0, r2, r0

// approximately 18 instruction slots used (4 texture, 14 arithmetic)
