//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by mhmca.rc
//
#define IDS_MAYHEM_MAP_CLASS_NAME       101
#define IDS_LIBDESC                     102
#define IDD_MAP_CUSTATTRIB              102
#define IDS_MAPCA                       103
#define IDB_MAYHEM_LOGO                 103
#define IDS_MAYHEM_GUP_CLASS_NAME       104
#define IDS_MAP_CUSTATTRIB              105
#define IDS_TESTCHECK                   106
#define IDS_MAPATTRIB_SPEEDU            107
#define IDS_MAPATTRIB_SPEEDV            108
#define IDS_MAPATTRIB_SPEEDROT          109
#define IDS_MAPATTRIB_MIPLEVEL          110
#define IDS_MAPATTRIB_COLORKEY_LOW      111
#define IDS_MAPATTRIB_COLORKEY_ENABLE   112
#define IDS_MAPATTRIB_COLORKEY_HI       113
#define IDS_MAPATTRIB_COLORKEY_ALPHA    114
#define IDS_MAPATTRIB_ALPHATEST_VALUE   115
#define IDS_MAPATTRIB_ALPHABLEND_ENABLE 116
#define IDS_MAPATTRIB_ADDITIVE_ENABLE   117
#define IDC_MAPATTRIB_SPEEDU            1009
#define IDC_MAPATTRIB_MIPLEVEL          1010
#define IDC_MAPATTRIB_SPEEDU_SPIN       1011
#define IDC_MAPATTRIB_SPEEDV            1012
#define IDC_MAPATTRIB_SPEEDV_SPIN       1013
#define IDC_MAPATTRIB_SPEEDROT          1014
#define IDC_MAPATTRIB_SPEEDROT_SPIN     1015
#define IDC_MAPATTRIB_MIPLEVEL_SPIN     1016
#define IDC_MAPATTRIB_COLORKEY_LOW      1017
#define IDC_MAPATTRIB_COLORKEY_ENABLE   1018
#define IDC_MAPATTRIB_COLORKEY_HI       1019
#define IDC_MAPATTRIB_COLORKEY_ALPHA    1020
#define IDC_MAPATTRIB_COLORKEY_ALPHA_SPIN 1021
#define IDC_MAPATTRIB_ALPHATEST_VALUE   1022
#define IDC_MAPATTRIB_ALPHATEST_VALUE_SPIN 1023
#define IDC_MAPATTRIB_ALPHABLEND_ENABLE 1024
#define IDC_MAPATTRIB_ADDITIVE_ENABLE   1025

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1025
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
